// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVqeiC__WY1zhjr67ZZqBJdGRZVwOnWkA',
    appId: '1:112112150748:web:272e8f0a2a6e1da1c9ac19',
    messagingSenderId: '112112150748',
    projectId: 'instagram-clone-9e589',
    authDomain: 'instagram-clone-9e589.firebaseapp.com',
    storageBucket: 'instagram-clone-9e589.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaWy-elYk8FeJxP04-EyfL1PrRWZD2Eq0',
    appId: '1:112112150748:android:f7f94dbb0e1cc80cc9ac19',
    messagingSenderId: '112112150748',
    projectId: 'instagram-clone-9e589',
    storageBucket: 'instagram-clone-9e589.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjzKlQKcbYgobwgo3nqiYUrLKmstNJa4I',
    appId: '1:112112150748:ios:e58a1300ca2ebf22c9ac19',
    messagingSenderId: '112112150748',
    projectId: 'instagram-clone-9e589',
    storageBucket: 'instagram-clone-9e589.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjzKlQKcbYgobwgo3nqiYUrLKmstNJa4I',
    appId: '1:112112150748:ios:e58a1300ca2ebf22c9ac19',
    messagingSenderId: '112112150748',
    projectId: 'instagram-clone-9e589',
    storageBucket: 'instagram-clone-9e589.firebasestorage.app',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVqeiC__WY1zhjr67ZZqBJdGRZVwOnWkA',
    appId: '1:112112150748:web:5bc581987c2d0c35c9ac19',
    messagingSenderId: '112112150748',
    projectId: 'instagram-clone-9e589',
    authDomain: 'instagram-clone-9e589.firebaseapp.com',
    storageBucket: 'instagram-clone-9e589.firebasestorage.app',
  );
}
